### ISSUE TITLE
Could some one help me understand the error!

### ISSUE THREAD

**Issue by aps5598** [tomopy/tomopy#235]
Traceback (most recent call last):
  File "New.py", line 52, in <module>
    f = h5py.File(file_name,"r")
  File "/storage/home/aps5598/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/storage/home/aps5598/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2696)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2654)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1942)
IOError: Unable to open file (File signature not found)

**Comment by dmpelt** [comment]
Could be that the h5 file is corrupted... What does running `h5ls file_name` in the terminal give as output?

**Comment by aps5598** [comment]
Instinctively, I just copied the data files in a new folder and changed the directory path and it worked!!
