### ISSUE TITLE
RTD build fails

### ISSUE THREAD

**Issue by dgursoy** [tomopy/tomopy#249]
Recently, RTD Sphinx build fails:

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tomopy/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tomopy/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tomopy/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension nbsphinx (exception: No module named jupyter_client.manager)

Extension error:
Could not import extension nbsphinx (exception: No module named jupyter_client.manager)
```

I haven't throughly checked but nbsphinx is already listed in the requirements-doc.txt. I suspect that there may be a compatibility issue with IPython?

**Comment by decarlof** [comment]
it seems jupyter_client.manager is now part of jupyter.
