### ISSUE TITLE
tomopy memory management

### ISSUE THREAD

**Issue by carterbox** [tomopy/tomopy#259]
I'm getting some confusing behavior from tomopy on Ubuntu 16.04, so I'd like to know a bit more about how tomopy manages memory and if the behavior I'm experiencing is expected.

When reconstructing on a chunk that is about 8GB (500 slices), the total RAM usage of my computer peaks around 10GB. However, the total memory footprint of `python` is reported to be between 16GB and 25GB.

The problem is that periodically my system slows to a crawl periodically because of lots of traffic to the main disk. However, the system never reports the RAM usage approaching anywhere near the 64GB that are available, and swap usage stays below 5MB so I know the system lag is not because system resources are being pushed to swap.

If a larger 16GB chunk is used `tomopy` will crash with this error message.
```bash
Traceback (most recent call last):
  File "reconstruct.py", line 133, in <module>
    reconstruct(fname, rot_center, proj_range)
  File "reconstruct.py", line 103, in reconstruct
    ncore=NCORES)
  File "/home/chingd/miniconda3/lib/python3.5/site-packages/tomopy/recon/algorithm.py", line 282, in recon
    recon = _init_recon(recon_shape, init_recon)
  File "/home/chingd/miniconda3/lib/python3.5/site-packages/tomopy/recon/algorithm.py", line 305, in _init_recon
    recon = dtype.empty_shared_array(shape)
  File "/home/chingd/miniconda3/lib/python3.5/site-packages/tomopy/util/dtype.py", line 184, in empty_shared_array
    shared_obj = mp.RawArray(ctype, int(size))
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/context.py", line 128, in RawArray
    return RawArray(typecode_or_type, size_or_initializer)
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/sharedctypes.py", line 60, in RawArray
    obj = _new_value(type_)
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/sharedctypes.py", line 40, in _new_value
    wrapper = heap.BufferWrapper(size)
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/heap.py", line 249, in __init__
    block = BufferWrapper._heap.malloc(size)
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/heap.py", line 231, in malloc
    (arena, start, stop) = self._malloc(size)
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/heap.py", line 129, in _malloc
    arena = Arena(length)
  File "/home/chingd/miniconda3/lib/python3.5/multiprocessing/heap.py", line 78, in __init__
    f.write(zeros)
OSError: [Errno 28] No space left on device
```
The key point is the last line. Which claims there is `no space left on device`, but system resources claims that the RAM was never fully utilized.

These behaviors lead me to believe that the data is being cached in a temp file on my harddisk instead of being stored in RAM where it would be more accessible not run out of space. If this is true, why is it true?

**Comment by dmpelt** [comment]
Which version of TomoPy are you running? Can you try with the latest (git) version? I'm asking because I think this is fixed by #217 . I was having similar problems (see at the end of #120 ), which is one of the reasons for creating #217 .

**Comment by carterbox** [comment]
I'm was running  `1.0.1` according to `conda`.

I tested 44bc5e0, and the behavior was more of what I expected.

**Comment by carterbox** [comment]
There still seems to be some unwanted caching to my root file system. Is there a way that I can displace this to another disk?

**Comment by dgursoy** [comment]
Is this still an issue?

**Comment by carterbox** [comment]
I don't know. I should try the workaround suggested [here](https://github.com/tomopy/tomopy/issues/120#issuecomment-226231631).
