### ISSUE TITLE
[Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Yggdrasil1** [tomopy/tomopy#279]
Hi, i am trying to get tomopy working.

The Imagetype i am working with is .edf, i can read them, add them to a 3D object, get the rotation center of my files and get the negative logarithm, but when i start the actual reconstruction it throws an error, that it cannot allocate memory. 
I know this may be more of an Ubuntu problem than an actual tomopy problem, but all other Scripts work perfectly fine. 

This is the series of tasks that throw the error:

runfile('/.../Programme/tomopy_test_2.py', wdir='.../Programme')

Center of rotation:  [ 981.6]
Traceback (most recent call last):

  File "<ipython-input-2-6632503f1179>", line 1, in <module>
    runfile('/.../Programme/tomopy_test_2.py', wdir='/.../Programme')

  File "/opt/processing/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/opt/processing/anaconda/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 94, in execfile
    builtins.execfile(filename, *where)

  File "/.../Programme/tomopy_test_2.py", line 77, in <module>
    rec = tomopy.recon(proj, theta, center=rot_center, algorithm='gridrec')

  File "/opt/processing/anaconda/lib/python2.7/site-packages/tomopy/recon/algorithm.py", line 282, in recon
    recon = _init_recon(recon_shape, init_recon)

  File "/opt/processing/anaconda/lib/python2.7/site-packages/tomopy/recon/algorithm.py", line 305, in _init_recon
    recon = dtype.empty_shared_array(shape) 

  File "/opt/processing/anaconda/lib/python2.7/site-packages/tomopy/util/dtype.py", line 184, in empty_shared_array
    shared_obj = mp.RawArray(ctype, int(size))

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/__init__.py", line 246, in RawArray
    return RawArray(typecode_or_type, size_or_initializer)

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/sharedctypes.py", line 88, in RawArray
    obj = _new_value(type_)

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/sharedctypes.py", line 68, in _new_value
    wrapper = heap.BufferWrapper(size)

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/heap.py", line 243, in __init__
    block = BufferWrapper._heap.malloc(size)

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/heap.py", line 223, in malloc
    (arena, start, stop) = self._malloc(size)

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/heap.py", line 120, in _malloc
    arena = Arena(length)

  File "/opt/processing/anaconda/lib/python2.7/multiprocessing/heap.py", line 82, in __init__
    self.buffer = mmap.mmap(-1, size)

error: [Errno 12] Cannot allocate memory

Can anybody help me and tell me what to do, so that the buffer can access the plenty of memory that my system has?

Thank you

**Comment by Yggdrasil1** [comment]
Okay, the Swap Partition is not existing, that explains a lot.
