### ISSUE TITLE
Can't run tomopy.prep.stripe.remove_stripe

### ISSUE THREAD

**Issue by alex83803** [tomopy/tomopy#394]
Dear comunity, 

I am quite new using tomopy and I have an issue while trying to run the tomopy.prep.stripe.remove_stripe_fw (as well as _ti and _sf) algorithm.

No matter how I install tomopy (setup or pip), I get the following error: 
```bash
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Neuer Ordner\Dropbox\python\Alex\tomopy\papier4.py", line 408, in <module>
    I = tomopy.prep.stripe.remove_stripe_fw(sinogram)
  File "D:\Neuer Ordner\Dropbox\python\Alex\tomopy\tomopy\prep\stripe.py", line 126, in remove_stripe_fw
    nchunk=nchunk)
  File "D:\Neuer Ordner\Dropbox\python\Alex\tomopy\tomopy\util\mproc.py", line 225, in distribute_jobs
    man = mp.Manager()
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\managers.py", line 513, in start
    self._process.start()
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Alex\Anaconda3\envs\alex\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFAB7833B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFB160956FD  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFB17933DC4  Unknown               Unknown  Unknown
ntdll.dll          00007FFB19133691  Unknown               Unknown  Unknown 

```

I have tried many things (new env, various ways to install tomopy) but cant figure out a way to use these stripe removal algorithms.

For instance, tomopy.misc.corr.remove_ring runs perfectly. 

Maybe you have an Idea about what my problem could me :-).

Thanks a lot for your support 

Kind regards

Alex

**Comment by carterbox** [comment]
Hi @alex83803, please see issue #356. I believe you are having the same problem. If it is the same, please close this issue. Otherwise, let me know that it is not solved.

**Comment by alex83803** [comment]
Dear Carterbox,
I am not sure this is the solution, I'll have a look at it :-)
Could you tell me how to implement this solution in the alex.py file?

Strangely the code works properly on my mac but not on my pc.

Thanks a lot for your time :-)

Regards

Alex

[alex.py.zip](https://github.com/tomopy/tomopy/files/2917795/alex.py.zip)

**Comment by carterbox** [comment]
As I stated in the other issue, this is a quirk of Windows python multiprocessing. It will only happen on machines running Windows.

As the error message says, you must protect the code in your script with an `if` statement. Change your script to follow this example:

```python
# Import all of the things
import os

# Define your functions
def _create_folder(file_path):
    file_base = os.path.dirname(file_path)
    if not os.path.exists(file_base):
        try:
            os.makedirs(file_base)
        except OSError as e:
            if e.errno != errno.EEXIST:
                raise

# Put the main operations of your script in a function called "main"
def main():
    image = imread("/Users/.../myimage.png")

    #INFO: I convert the 3D Array file into a 2D Array
    if len(image.shape) > 2:
        axis_m = np.argmin(image.shape)
        image = np.mean(image, axis=axis_m)

    # do more stuff...

# Here is the `if` statement that protects your code
if __name__ == '__main__':
    freeze_support()  # only needed if you are making an `.exe` file
    main()
```

**Comment by alex83803** [comment]
Dear Carterbox,

thank you so much for your help.

I wish you a great weekend.

**Comment by carterbox** [comment]
You're welcome! Happy sciencing! :nerd_face:
