### ISSUE TITLE
remove_all_stripe algorithm definitions missing

### ISSUE THREAD

**Issue by jdgelb** [tomopy/tomopy#426]
Hi all! I am trying to run the remove_all_stripe method on Windows, but I'm getting an error:

```
Traceback (most recent call last):
  File "C:/Users/Sigray/PycharmProjects/sigraytools/Reconstruction/reconstruction.py", line 776, in <module>
    main(sys.argv[1:])
  File "C:/Users/Sigray/PycharmProjects/sigraytools/Reconstruction/reconstruction.py", line 534, in main
    proj = tomopy.remove_all_stripe(proj, ncore=number_of_cores)
  File "C:\Users\Sigray\AppData\Local\Continuum\anaconda3\lib\site-packages\tomopy\prep\stripe.py", line 833, in remove_all_stripe
    nchunk=nchunk)
  File "C:\Users\Sigray\AppData\Local\Continuum\anaconda3\lib\site-packages\tomopy\util\mproc.py", line 330, in distribute_jobs
    _arg_parser(m)
  File "C:\Users\Sigray\AppData\Local\Continuum\anaconda3\lib\site-packages\tomopy\util\mproc.py", line 384, in _arg_parser
    result = func(*func_args, **kwargs)
  File "C:\Users\Sigray\AppData\Local\Continuum\anaconda3\lib\site-packages\tomopy\prep\stripe.py", line 841, in _remove_all_stripe
    sino = _rs_algorithm_6(sino, snr, la_size, matindex)
NameError: name '_rs_algorithm_6' is not defined
```

This is running TomoPy version 1.5.0 on Windows 10. It seems like there maybe is some issue finding algorithm 6? Anybody else see this on Windows? (I haven't yet gotten access to a linux workstation to check in the "native" environment :-) )

**Comment by carterbox** [comment]
This is not a Windows specific problem. `_rs_algorithm_6` and `rs_algorithm_3` are not defined anywhere in TomoPy.

**Comment by nghia-vo** [comment]
My mistake. I changed the name of these function but forgot to update 
_rs_algorithm_6 -> _rs_dead  
_rs_algorithm_3 -> _rs_sort 
will correct this

**Comment by jdgelb** [comment]
Thanks both! Really enjoyed reading the paper on this topic... I'm looking forward to test driving Nghia's routine. (the combined one that I have nicknamed "The Sledgehammer")

**Comment by dgursoy** [comment]
@jdgelb: I like the idea of using synonym function names for fun. 

```python
def sledgehammer(args):
    return remove_all_stripe(args)
```

**Comment by prjemian** [comment]
Why not even a true synonym then?

    sledgehammer = remove_all_stripe
