### ISSUE TITLE
TomoPy Fresh Install Fails on Windows 10

### ISSUE THREAD

**Issue by bluepotatoes** [tomopy/tomopy#528]
This happened on windows 10 with a fresh version of miniconda in a fresh environment. 
`conda create --name tomopy --channel conda-forge tomopy`
`conda activate tomopy`

```python
>>> import tomopy
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-54dce91d8069> in <module>
----> 1 import tomopy

~\Miniconda3\envs\tomopy\lib\site-packages\tomopy\__init__.py in <module>
     61 
     62 from ._fft_loader import fft_impl
---> 63 from tomopy.misc.corr import *
     64 from tomopy.misc.morph import *
     65 from tomopy.misc.phantom import *

~\Miniconda3\envs\tomopy\lib\site-packages\tomopy\misc\corr.py in <module>
     58 import tomopy.util.mproc as mproc
     59 import tomopy.util.dtype as dtype
---> 60 import tomopy.util.extern as extern
     61 import logging
     62 import warnings

~\Miniconda3\envs\tomopy\lib\site-packages\tomopy\util\extern\__init__.py in <module>
     83 from tomopy.util.extern.recon import *
     84 from tomopy.util.extern.accel import *
---> 85 from tomopy.util.extern.gridrec import *
     86 from tomopy.util.extern.prep import *
     87 from tomopy.util.extern.misc import *

~\Miniconda3\envs\tomopy\lib\site-packages\tomopy\util\extern\gridrec.py in <module>
     60 
     61 
---> 62 LIB_TOMOPY_GRIDREC = c_shared_lib("libtomopy-gridrec", error=False)
     63 
     64 

~\Miniconda3\envs\tomopy\lib\site-packages\tomopy\util\extern\__init__.py in c_shared_lib(lib_name, error)
     65     sharedlib = os.path.join(base_path, '%s%s' % (lib_name, ext))
     66     if os.path.exists(sharedlib):
---> 67         return load_dll(sharedlib)
     68     if error:
     69         raise ModuleNotFoundError(

~\Miniconda3\envs\tomopy\lib\ctypes\__init__.py in LoadLibrary(self, name)
    458 
    459     def LoadLibrary(self, name):
--> 460         return self._dlltype(name)
```

**Comment by bluepotatoes** [comment]
```~\Miniconda3\envs\tomopy\lib\ctypes\__init__.py in LoadLibrary(self, name)
    458 
    459     def LoadLibrary(self, name):
--> 460         return self._dlltype(name)
    461 
    462     __class_getitem__ = classmethod(_types.GenericAlias)

~\Miniconda3\envs\tomopy\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    380 
    381         if handle is None:
--> 382             self._handle = _dlopen(self._name, mode)
    383         else:
    384             self._handle = handle

FileNotFoundError: Could not find module 'C:\Users\mjc5455\Miniconda3\envs\tomopy\lib\site-packages\tomopy\util\extern\libtomopy-gridrec.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by bluepotatoes** [comment]
```python
   461 
    462     __class_getitem__ = classmethod(_types.GenericAlias)

~\Miniconda3\envs\tomopy\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    380 
    381         if handle is None:
--> 382             self._handle = _dlopen(self._name, mode)
    383         else:
    384             self._handle = handle

FileNotFoundError: Could not find module 'C:\Users\[REDACTED]\Miniconda3\envs\tomopy\lib\site-packages\tomopy\util\extern\libtomopy-gridrec.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by bluepotatoes** [comment]
Just realized that this is only happening in Jupyter ...

The Python REPL still works.  

Probably not a valid issue, then.

**Comment by bluepotatoes** [comment]
https://github.com/jupyter/notebook/issues/4569

**Comment by carterbox** [comment]
@bluepotatoes Glad that you figured it out? If you determine that something can be changed in TomoPy to fix this problem please reopen this issue.

**Comment by bluepotatoes** [comment]
Hi Carter, 

While I have no problem installing Tomopy and Astra in separate environments, I can't seem to prevent a clash when installing from Conda on windows 10

```
conda install -c conda-forge -c astra-toolbox astra-toolbox tomopy
>>> import tomopy

  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\tomopy\__init__.py", line 65, in <module>
    from tomopy.misc.phantom import *
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\tomopy\misc\phantom.py", line 57, in <module>
    import skimage
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\skimage\__init__.py", line 157, in <module>
    from .util.dtype import *
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\skimage\util\__init__.py", line 6, in <module>
    from .apply_parallel import apply_parallel
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\skimage\util\apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\dask\array\__init__.py", line 2, in <module>
    from .blockwise import blockwise, atop
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\dask\array\blockwise.py", line 259, in <module>
    from .core import new_da_object
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\dask\array\core.py", line 22, in <module>
    from . import chunk
  File "C:\Users\XXX\Miniconda3\envs\tomoastra\lib\site-packages\dask\array\chunk.py", line 17, in <module>
    take_along_axis = npcompat.take_along_axis
AttributeError: module 'dask.array.numpy_compat' has no attribute 'take_along_axis'
```

This is with a conda distribution of Python 3.6.12.

Do you have any advice as to what I can do? I tried installing Astra first, then tomopy. I tried tompy followed by Astra.  I have tried on python 3.5 and 3.6.
Generally I got environment clashes that conda couldn't resolve. 

Python 3.5 and installing both on one line gets past the conda conflicts, but the import fails. Is there any trick to getting conda to resolve these problems? 

Sorry for the trouble.

**Comment by bluepotatoes** [comment]
The one-line install is in a clean environment, by the way.  Not even a python install is in that environment.

**Comment by carterbox** [comment]
@bluepotatoes, please use `astra-toolbox=1.9` as recommended on their downloads page; install at the same time with TomoPy.

**Comment by bluepotatoes** [comment]
Thank you so much! Didn't realize that I had to use the /labels/dev channel for astra.  

Conda did go ahead and install scikit-image 0.16.2 by default, which throws an error when importing tomopy because the it lacks the phase_cross_correlation.  Not a big issue but thought I'd let you know. 

Anyways, everything works now.  Thanks for the help.

**Comment by sgxx** [comment]
FileNotFoundError: Could not find module 'libtomopy-gridrec.dll' (or one of its dependencies). Try using the full path with constructor syntax.
How to resolve this problem?
