### ISSUE TITLE
TypeError: cannot pickle 'memoryview' object when using multiple core during tomopy.prep.alignment.align_joint

### ISSUE THREAD

**Issue by maloeffl** [tomopy/tomopy#645]
I want to use tomopy to align the projections using the align_joint function

**To Reproduce (if applicable)**
`proj=tomopy.prep.alignment.align_joint(proj, angles, fdir='./', iters=3, pad=(4, 4), blur=True, center=None, algorithm='gridrec', upsample_factor=1, rin=0.5, rout=0.8, save=False, debug=True)`
proj contains the (201) projections, angles is a list of projection angles

```
proj=tomopy.prep.alignment.align_joint(proj, angles, fdir='./', iters=3, pad=(4, 4), blur=True, center=None, algorithm='gridrec', upsample_factor=1, rin=0.5, rout=0.8, save=False, debug=True)
Traceback (most recent call last):

  File "C:\Users\dcnlab\AppData\Local\Temp\ipykernel_10248\2958958457.py", line 1, in <module>
    proj=tomopy.prep.alignment.align_joint(proj, angles, fdir='./', iters=3, pad=(4, 4), blur=True, center=None, algorithm='gridrec', upsample_factor=1, rin=0.5, rout=0.8, save=False, debug=True)

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\site-packages\tomopy\prep\alignment.py", line 314, in align_joint
    sim = project(rec, ang, center=center, pad=False)

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\site-packages\tomopy\sim\project.py", line 320, in project
    tomo = mproc.distribute_jobs(

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\site-packages\tomopy\util\mproc.py", line 298, in distribute_jobs
    with closing(mp.Pool(processes=ncore,

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

TypeError: cannot pickle 'memoryview' object


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\dcnlab\Anaconda3\envs\tomo\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Expected behavior (if applicable)**
Alignment of projections

**Helpful images (if applicable)**
Add screenshots to help explain your problem.

**Platform Information:**
Windows 10, Anaconda, Python 3.9

**Additional context**
Function does not throw an error when changing ncore to1 in project.py in 

```
def project(
        obj, theta, center=None, emission=True, pad=True,
        sinogram_order=False, ncore=None, nchunk=None):
    """
    Project x-rays through a given 3D object.

    Parameters
    ----------
    obj : ndarray
        Voxelized 3D object.
    theta : array
        Projection angles in radian.
    center: array, optional
        Location of rotation axis.
    emission : bool, optional
        Determines whether output data is emission or transmission type.
    pad : bool, optional
        Determines if the projection image width will be padded or not. If True,
        then the diagonal length of the object cross-section will be used for the
        output size of the projection image width.
    sinogram_order: bool, optional
        Determines whether output data is a stack of sinograms (True, y-axis first axis)
        or a stack of radiographs (False, theta first axis).
    ncore : int, optional
        Number of cores that will be assigned to jobs.
    nchunk : int, optional
        Chunk size for each core.

    Returns
    -------
    ndarray
        3D tomographic data.
    """
    obj = dtype.as_float32(obj)
    theta = dtype.as_float32(theta)

    # Estimate data dimensions.
    oy, ox, oz = obj.shape
    dt = theta.size
    dy = oy
    if pad is True:
        dx = _round_to_even(np.sqrt(ox * ox + oz * oz) + 2)
    elif pad is False:
        dx = ox
    shape = dy, dt, dx
    tomo = dtype.empty_shared_array(shape)
    tomo[:] = 0.0
    center = get_center(shape, center)

    tomo = mproc.distribute_jobs(
        (obj, center, tomo),
        func=extern.c_project,
        args=(theta,),
        axis=0,
        ncore=1, #changed ncore=ncore to ncore=1
        nchunk=nchunk)
    # NOTE: returns sinogram order with emmission=True
    if not emission:
        # convert data to be transmission type
        np.exp(-tomo, tomo)
    if not sinogram_order:
        # rotate to radiograph order
        tomo = np.swapaxes(tomo, 0, 1)  # doesn't copy data
        # copy data to sharedmem
        tomo = dtype.as_sharedmem(tomo, copy=True)

    return tomo
```

**Comment by carterbox** [comment]
> TypeError: cannot pickle 'memoryview' object

This error means that TomoPy is trying to send a view of a NumPy array between processes instead of an array, and apparently that is not allowed. Python objects are pickled before being sent between workers when using the multiprocess library.
