### ISSUE TITLE
tomopy.misc.corr.remove_ring() executing succesfully without returning modified array

### ISSUE THREAD

**Issue by aethrist** [tomopy/tomopy#646]
I've been writing up a small GUI to apply the ring removal filter to some already reconstructed tif stacks I have. It all works fine and well. However, the function tomopy.misc.corr.remove_ring() does not return any modified result but the original array.  

This is the button click event:
```python

def fullVolClick(self): 
        self.ringRem.set_tifParams(self.tifParams)
        center, _ = self.canvasClick.get_circleParams()
        self.getRingRemKwargs()
        self.ringRem.removeRingTomopy(self.tiffs, 
                                center_x = center[0],
                                center_y = center[1], 
                                **self.ringRemKwargs)
        self.tifImage.set_data(self.ringRem.ringRemTif[self.tifParams["z"],:,:])
        self.canvas.draw()

```

This is the class it takes from. It is initialized on the gui main window level. Using deepcopy was my latest attempt to maybe fix some weird reference issues but it didn't work: 

```python

class RingRemoval():
        def set_tifParams(self, tifParams):
            self.tifParams = tifParams

        def removeRingTomopy(self, tiffs, **kwargs): 
            tiffsCopy = copy.deepcopy(np.asarray(tiffs, dtype = "float32"))
            self.ringRemTif = tomopy.misc.corr.remove_ring(tiffsCopy, **kwargs)
```

Another, potentially connected issue that I had with the function, was caused by an incompatibility between numpy version where I had to make sure to specify float32 as dtype before I could move on: 

```
Traceback (most recent call last):
  File "/mnt/d/tristan/tomopy/ringRemoval.py", line 258, in previewClick
    self.ringRem.removeRing(np.expand_dims(self.tiffs[self.tifParams["z"],:,:], axis = 0), 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/user/tomopy/ringRemoval.py", line 305, in removeRing
    tiffs   = tomopy.misc.corr.remove_ring(tiffs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/99_pyenvs/pyimagej_tomo/lib/python3.12/site-packages/tomopy/misc/corr.py", line 792, in remove_ring
    rec = dtype.as_float32(rec)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/99_pyenvs/pyimagej_tomo/lib/python3.12/site-packages/tomopy/util/dtype.py", line 100, in as_float32
    return as_dtype(arr, np.float32)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/99_pyenvs/pyimagej_tomo/lib/python3.12/site-packages/tomopy/util/dtype.py", line 94, in as_dtype
    arr = np.array(arr, dtype=dtype, copy=copy)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

**Expected behavior (if applicable)**
Return properly modified array. 

**Platform Information:**
 - OS: Windows 10 with python running in Ubuntu 22.04.4 LTS running on WSL1 
 - Python Version 3.12.5
 Conda environment with following packages: [packagelist2.txt](https://github.com/user-attachments/files/16600956/packagelist2.txt)

**Comment by aethrist** [comment]
Small update: I installed a new conda environment in a downgraded python version 3.10.14 with tomopy, pyqt, (and pyparsing because that didn't install through the pyqt dependencies). Even though that did solve the incompatibility between the numpy versions, the original bug still persists.
