### ISSUE TITLE
tomo-recon was not found

### ISSUE THREAD

**Issue by GueroudjiAmal** [tomopy/tomopy#653]
**Describe the problem**
Trying to use py-tomopy in a spack environment. 

**To Reproduce **

`spack install py-tomopy@master`
`import tomopy`

others:
(```python) make code blocks readable.

```python
import tomopy # error happens here
```

```
Python 3.11.9 (main, Dec  2 2024, 04:11:28) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tomopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/spack/var/spack/environments/support/.spack-env/view/lib/python3.11/site-packages/tomopy/__init__.py", line 65, in <module>
    from tomopy.misc.corr import *
  File "/home/spack/var/spack/environments/support/.spack-env/view/lib/python3.11/site-packages/tomopy/misc/corr.py", line 56, in <module>
    import tomopy.util.extern as extern
  File "/home/spack/var/spack/environments/support/.spack-env/view/lib/python3.11/site-packages/tomopy/util/extern/__init__.py", line 97, in <module>
    from tomopy.util.extern.recon import *
  File "/home/spack/var/spack/environments/support/.spack-env/view/lib/python3.11/site-packages/tomopy/util/extern/recon.py", line 83, in <module>
    LIB_TOMOPY_RECON = c_shared_lib("tomo-recon")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spack/var/spack/environments/support/.spack-env/view/lib/python3.11/site-packages/tomopy/util/extern/__init__.py", line 80, in c_shared_lib
    raise ModuleNotFoundError(
ModuleNotFoundError: TomoPy links to compiled components which are installed separately and loaded using ctypes.util.find_library(). A required library, tomo-recon, was not found.
```
**Versions:**
spack: 0.24.0.dev0 (ac82f344bd8e1da704a8aa346bd77b3d65ee198d)
python: 3.11.9
tomopy: master 
**Platform Information:**
ALCF Polaris

**Comment by jnahlers** [comment]
Getting the same error when trying to run tomophantom in a [`pixi`](https://pixi.sh/latest/]) environment in VS Code.

**Comment by carterbox** [comment]
AFAIK, the maintainers of tomopy do not maintain the spack package for tomopy, we only publish a conda package. Please contact the publishers of the spack package for assistance.
