### ISSUE TITLE
Conda installed latest tomopy but couldn't run test successfully

### ISSUE THREAD

**Issue by celiafish** [tomopy/tomopy#75]
$ python test_recon.py 
No handlers could be found for logger "tomopy.prep"
EEEEEEEEEEEE
======================================================================
ERROR: __main__.test_simulate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 82, in test_simulate
    out = simulate(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 136, in simulate
    LIB_TOMOPY.simulate.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'simulate'

======================================================================
ERROR: __main__.test_gridrec
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 88, in test_gridrec
    out = gridrec(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 209, in gridrec
    LIB_TOMOPY.gridrec.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'gridrec'

======================================================================
ERROR: __main__.test_art
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 94, in test_art
    out = art(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 284, in art
    LIB_TOMOPY.art.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'art'

======================================================================
ERROR: __main__.test_bart
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 100, in test_bart
    out = bart(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 366, in bart
    LIB_TOMOPY.bart.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'bart'

======================================================================
ERROR: __main__.test_fbp
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 106, in test_fbp
    out = fbp(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 435, in fbp
    LIB_TOMOPY.fbp.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'fbp'

======================================================================
ERROR: __main__.test_mlem
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 112, in test_mlem
    out = mlem(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 505, in mlem
    LIB_TOMOPY.mlem.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'mlem'

======================================================================
ERROR: __main__.test_osem
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 118, in test_osem
    out = osem(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 587, in osem
    LIB_TOMOPY.osem.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'osem'

======================================================================
ERROR: __main__.test_ospml_hybrid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 124, in test_ospml_hybrid
    out = ospml_hybrid(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 678, in ospml_hybrid
    LIB_TOMOPY.ospml_hybrid.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'ospml_hybrid'

======================================================================
ERROR: __main__.test_ospml_quad
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 130, in test_ospml_quad
    out = ospml_quad(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 769, in ospml_quad
    LIB_TOMOPY.ospml_quad.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'ospml_quad'

======================================================================
ERROR: __main__.test_pml_hybrid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 136, in test_pml_hybrid
    out = pml_hybrid(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 855, in pml_hybrid
    LIB_TOMOPY.pml_hybrid.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'pml_hybrid'

======================================================================
ERROR: __main__.test_pml_quad
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 142, in test_pml_quad
    out = pml_quad(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 935, in pml_quad
    LIB_TOMOPY.pml_quad.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'pml_quad'

======================================================================
ERROR: __main__.test_sirt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wxu/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "test_recon.py", line 148, in test_sirt
    out = sirt(synthetic_data(), theta=(0., 1.))
  File "/home/wxu/anaconda/lib/python2.7/site-packages/tomopy/recon.py", line 1007, in sirt
    LIB_TOMOPY.sirt.restype = ctypes.POINTER(ctypes.c_void_p)
AttributeError: 'NoneType' object has no attribute 'sirt'

----------------------------------------------------------------------
Ran 12 tests in 0.004s

FAILED (errors=12)

**Comment by dgursoy** [comment]
#76 should fix that. Can you give it a try again?

**Comment by celiafish** [comment]
Yes, it was fixed. Thanks!

**Comment by dgursoy** [comment]
Great!
