### ISSUE TITLE
Issue about find_center

### ISSUE THREAD

**Issue by licode** [tomopy/tomopy#87]
I am running the standard examples with find_center function.
```
def run_sim_data():
    obj = tomopy.shepp3d() # Generate an object.
    ang = tomopy.angles(180) # Generate uniformly spaced tilt angles.
    sim = tomopy.project(obj, ang) # Calculate projections.

    cen = tomopy.find_center(sim, ang)
    rec = tomopy.recon(sim, ang, center=cen, algorithm='art')
```
And I got the following error.

Traceback (most recent call last):
  File "tomo_xrf.py", line 52, in <module>
    run_sim_data()
  File "tomo_xrf.py", line 12, in run_sim_data
    cen = tomopy.find_center(sim, ang)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/tomopy/recon/rotation.py", line 120, in find_center
    rec = gridrec(tomo[:, ind:ind + 1, :], theta, emission=emission)
NameError: global name 'gridrec' is not defined
 
Thanks for any suggestions!

**Comment by dgursoy** [comment]
#88 should fix that. Let me know if it works.

**Comment by licode** [comment]
Hi Doga,

I used conda install "conda install -c https://conda.binstar.org/dgursoy tomopy", and check "conda list" that the tomopy version is already 0.1.8.

But I still got the following error when I try the same example.

/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/PIMS-0.2.0-py2.7-linux-x86_64.egg/_tifffile.py:3: UserWarning: Module _tifffile was already imported from /home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/PIMS-0.2.0-py2.7-linux-x86_64.egg/_tifffile.pyc, but /home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/tifffile-2014.8.24-py2.7-linux-x86_64.egg is being added to sys.path
Trying center:  [ 91.]
Traceback (most recent call last):
  File "tomo_xrf.py", line 52, in <module>
    run_sim_data()
  File "tomo_xrf.py", line 12, in run_sim_data
    cen = tomopy.find_center(sim, ang)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/tomopy/recon/rotation.py", line 137, in find_center
    tol=tol)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/scipy/optimize/_minimize.py", line 413, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 433, in _minimize_neldermead
    fsim[0] = func(x0)
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 282, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/lili/mc/envs/my_analysis/lib/python2.7/site-packages/tomopy/recon/rotation.py", line 155, in _find_center_cost
    rec = gridrec(tomo[:, ind:ind + 1, :], theta, center, emission)
NameError: global name 'gridrec' is not defined

**Comment by dgursoy** [comment]
My bad. Please try updating to 0.1.9 and try again.

**Comment by licode** [comment]
Thanks. It works.
